package com.sirajchaudhary.propertyfinder.dto.response;

import java.time.LocalDateTime;
import java.util.List;

/*
 * ============================================================================
 * Error Response
 * ============================================================================
 *
 * Standard response returned whenever an API request fails.
 *
 * Responsibilities:
 *
 * - Provide a consistent error response format.
 * - Help API consumers understand why a request failed.
 * - Return validation errors when multiple fields are invalid.
 * - Include useful debugging information.
 *
 * This response is generated by the GlobalExceptionMapper and is returned
 * for all handled exceptions throughout the application.
 *
 * Example:
 *
 * {
 *   "timestamp": "2026-07-12T15:30:45",
 *   "status": 400,
 *   "error": "Bad Request",
 *   "message": "Validation failed",
 *   "path": "/api/v1/properties",
 *   "errors": [
 *     "Title is required",
 *     "Price must be greater than zero"
 *   ]
 * }
 *
 */
public record ErrorResponse(

        /**
         * Date and time when the error occurred.
         */
        LocalDateTime timestamp,

        /**
         * HTTP status code.
         *
         * Examples:
         *
         * - 400
         * - 404
         * - 409
         * - 500
         */
        int status,

        /**
         * HTTP status description.
         *
         * Examples:
         *
         * - Bad Request
         * - Not Found
         * - Conflict
         * - Internal Server Error
         */
        String error,

        /**
         * Human-readable error message.
         */
        String message,

        /**
         * Requested API endpoint.
         *
         * Example:
         *
         * /api/v1/properties/10
         */
        String path,

        /**
         * Collection of validation or business errors.
         *
         * This list is typically populated for validation failures where
         * multiple fields may be invalid simultaneously.
         */
        List<String> errors

) {
}