# ==========================================================================
# Application Configuration
# ==========================================================================

quarkus.application.name=property-finder-service

# ==========================================================================
# HTTP Configuration
# ==========================================================================

quarkus.http.port=8080

# ==========================================================================
# PostgreSQL Datasource Configuration
# ==========================================================================

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=siraj123

quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/propertyfinderdb

# Use this datasource URL when running the application inside a Docker container while PostgreSQL is running on the host machine.
# quarkus.datasource.jdbc.url=jdbc:postgresql://host.docker.internal:5432/propertyfinderdb

# ==========================================================================
# Hibernate ORM Configuration
# ==========================================================================

quarkus.hibernate-orm.schema-management.strategy=validate

quarkus.hibernate-orm.log.sql=true

quarkus.hibernate-orm.log.format-sql=true

# ==========================================================================
# Logging Configuration
# ==========================================================================

quarkus.log.level=INFO

quarkus.log.category."com.sirajchaudhary.propertyfinder".level=DEBUG

# ==========================================================================
# OpenAPI & Swagger UI
# ==========================================================================

quarkus.swagger-ui.always-include=true

quarkus.smallrye-openapi.info-title=Property Finder Service API

quarkus.smallrye-openapi.info-version=1.0.0

quarkus.smallrye-openapi.info-description=Cloud Native Property Finder Service built with Quarkus.

# ==========================================================================
# Health Endpoint
# ==========================================================================

quarkus.smallrye-health.root-path=/health
